#!/bin/bash
# Install git hooks so `git pull` auto-rebuilds + restarts the app.
# Run once per clone:  ./tools/install-hooks.sh
# (git hooks live in .git/hooks, which is NOT version-controlled, so each
# clone has to install them once.)
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$REPO_DIR/.git/hooks/post-merge"

cat > "$HOOK" <<'EOF'
#!/bin/sh
# Auto-generated by tools/install-hooks.sh — rebuild macmonitor after `git pull`.
ROOT="$(git rev-parse --show-toplevel)"
echo "[post-merge] rebuilding macmonitor..."
"$ROOT/tools/rebuild.sh"
EOF

chmod +x "$HOOK"
echo "installed: $HOOK"
echo "From now on, 'git pull' that brings in changes will rebuild + restart the app."
